plugins {
    id 'java-library'
    id 'maven-publish'
}

ext.pomName = 'RSF Framework'
description = 'RSF framework with configuration, context assembly, RPC, service container, addresses, serialization and Neta transports.'

dependencies {
    api "net.hasor:cobble-all:${property('lib.cobble')}"
    api "net.hasor:neta-core:${property('lib.neta')}"
    api "net.hasor:neta-codec-http:${property('lib.neta')}"
    api "org.codehaus.groovy:groovy:${property('lib.groovy')}"

    implementation "org.slf4j:slf4j-api:${property('lib.slf4j')}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${property('lib.jackson')}"
    implementation "com.caucho:hessian:${property('lib.hessian')}"
}
