<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.hasor</groupId>
        <artifactId>rsf-parent</artifactId>
        <version>4.2.6-SNAPSHOT</version>
    </parent>

    <!-- Maven Info -->
    <artifactId>rsf-core</artifactId>
    <packaging>jar</packaging>

    <!-- Project Info -->
    <name>RSF Framework</name>
    <description>request/response RPC Framework.</description>

    <developers>
        <developer>
            <name>赵永春(Mr.Zhao)</name>
            <email>zyc@hasor.net</email>
        </developer>
    </developers>

    <!-- 引用依赖 -->
    <dependencies>
        <dependency>
            <groupId>net.hasor</groupId>
            <artifactId>cobble-all</artifactId>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
        </dependency>

        <dependency>
            <groupId>org.hprose</groupId>
            <artifactId>hprose-java</artifactId>
            <version>2.0.38</version>
            <scope>compile</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.caucho</groupId>
            <artifactId>hessian</artifactId>
            <version>4.0.63</version>
            <scope>compile</scope>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>